name: gg_template_project
description: The gg_template_project package provides various JSON helpers for dart
version: 1.1.0
repository: https://github.com/ggsuite/gg_template_project.git
publish_to: none

environment:
  sdk: ">=3.13.0 <4.0.0"

dependencies:
  path: ^1.9.1

dev_dependencies:
  dna_base: ^0.1.0
  helix: ^0.1.0
  lints: ^6.1.0
  test: ^1.31.2